// ambil gambar
// import imageMenu1 from "./src/assets/menu-option-1.png";
// import imageMenu2 from "./src/assets/menu-option-2.png";
// import imageMenu3 from "./src/assets/menu-option-3.png";
// import imageMenu4 from "./src/assets/menu-option-4.png";
// import imageMenu5 from "./src/assets/menu-option-5.png";

export const navData = [
  { name: "HOME", id: "home", type: "scroll" },
  { name: "Reservations", id: "reservations", type: "dropdown" },
  { name: "menu", id: "/blog-kami", type: "link" },
  { name: "FAQs", id: "https://wa.me/12345678910", type: "scroll" },
  { name: "Our Service", id: "https://wa.me/12345678910", type: "scroll" },

  // {
  //   name: "INSTAGRAM",
  //   id: "https://instagram.com",
  //   type: "icon",
  //   icon: "instagram",
  // },
  // {
  //   name: "WHATSAPP",
  //   id: "https://wa.me/123456789",
  //   type: "icon",
  //   icon: "whatsapp",
  // },
  // {
  //   name: "TIKTOK",
  //   id: "https://titkok.com",
  //   type: "icon",
  //   icon: "tiktok",
  // },
];

export const ourMenuItems = [
  { label: "Main menu", path: "/menu-option" },
  { label: "Rice Bowl", path: "/menu-option" },
  { label: "Noodle and Pasta", path: "/menu-option" },
  { label: "PIZZA", path: "/menu-option" },
  { label: "Dessert", path: "/menu-option" },
  { label: "Bites", path: "/menu-option" },
  { label: "Coffe Based", path: "/menu-option" },
  { label: "KINI Signature", path: "/menu-option" },
  { label: "Coffe Mocktail", path: "/menu-option" },
  { label: "Flavored tea", path: "/menu-option" },
  { label: "Milk Shake", path: "/menu-option" },
  { label: "Fancy Mocktail", path: "/menu-option" },
  { label: "Juice", path: "/menu-option" },
  { label: "Powder Based", path: "/menu-option" },
  { label: "Mineral Water", path: "/menu-option" },
];
// data review
export const testimonial = [
  {
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol.`,
    note: "Note: Max. 380 Character",
  },
  {
    date: "1 tahun yang lalu",
    name: "Kim jong un",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.Lorem ipsum dol`,
    note: "Note: Max. 380 Character",
  },
];

// data untuk menuoption
// data.jsx

export const menuCategories = [
  {
    name: "Main menu",
    posts: [
      {
        id: 1,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 5,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 2,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 3,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 4,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 5,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 6,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 7,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 8,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 9,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 10,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 11,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
      {
        id: 12,
        title: "Chicken Steak",
        price: "Rp. 61.886",
        // commentCount: 3,
        // shareCount: 2,
        // image: imageMenu1,
      },
    ],
  },
  {
    name: "Heavy Meal",
    posts: [
      {
        id: 1,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 2,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 3,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 4,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 5,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 6,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 7,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 8,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 9,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 10,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 11,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
      {
        id: 12,
        title: "Ayam Bakar Andaliman",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu2,
      },
    ],
  },
  {
    name: "Light Meals",
    posts: [
      {
        id: 1,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 2,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 3,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 4,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 5,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 6,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 7,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 8,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 9,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 10,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 11,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
      {
        id: 12,
        title: "Lava Cake",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu3,
      },
    ],
  },
  {
    name: "Heavy Drinks",
    posts: [
      {
        id: 1,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 2,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 3,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 4,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 5,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 6,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 7,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 8,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 9,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 10,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 11,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
      {
        id: 12,
        title: "Cappucino",
        price: "Rp. 61.886",
        // commentCount: 29,
        // shareCount: 16,
        // image: imageMenu4,
      },
    ],
  },
  {
    name: "Light Drinks",
    posts: [
      {
        id: 1,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 2,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 3,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 4,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 5,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 6,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 7,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 8,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 9,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 10,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 11,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
      {
        id: 12,
        title: "Lemon Honey Tea",
        price: "Rp. 61.886",
        // image: imageMenu5,
      },
    ],
  },
];
